name: Node CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: test pull request
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test
